export type Entity = {
  crestLocales?: Record<string, { name: string; text: string }>;
  triggerLimits?: { abilityId: string; turnScope: "own" | "oppo" | "any"; used: boolean }[];
  grantedAbilities?: { kind: string; labels?: Record<string, string> }[];
  counters?: Record<string, number>;
  fusion?: FusionState;
  instanceId: string;
  cardId: number;
  cost?: number;
  attack?: number;
  life?: number;
  maxLife?: number;
  cardType: string;
  keywords?: string[];
  evolved?: boolean;
  superEvolved?: boolean;
  earthsigil?: number;
  countdown?: number;
  damageReduction?: number;
  attackLimit?: number;
  attacksUsed?: number;
  summoningSick?: boolean;
};
export type FusionState = {
  enabled: boolean;
  usedThisTurn: boolean;
  totalCost: number;
  distinctKinds: number;
  materials: { cardId: number; cost: number }[];
};
export type LegalAction = { kind: string; actor: string; source?: string; defender?: string };
export type ChoiceCandidate = { kind: string; instanceId?: string; leaderSide?: string; optionId?: number; labels?: Record<string, string> };
export type ChoiceRequest = {
  requestId: string;
  actionId: string;
  kind: string;
  minSelections: number;
  maxSelections: number;
  candidates: ChoiceCandidate[];
  stateRevision: number;
};
export type RuntimeTarget = {
  instanceId?: string; InstanceID?: string;
  kind?: string; Kind?: string;
  side?: string; Side?: string;
  cardId?: number; CardID?: number;
};
export type RuntimeEvent = RuntimeTarget & {
  actual?: number; Actual?: number;
  count?: number; Count?: number;
  subject?: RuntimeTarget; Subject?: RuntimeTarget;
  target?: RuntimeTarget; Target?: RuntimeTarget;
  attacker?: RuntimeTarget; Attacker?: RuntimeTarget;
  defender?: RuntimeTarget; Defender?: RuntimeTarget;
  sequence?: number; Sequence?: number;
  from?: string; From?: string;
  to?: string; To?: string;
};
export type PlayerView = {
  crests?: Entity[];
  leaderLife: number;
  leaderMax: number;
  pp: number;
  maxpp: number;
  ep: number;
  sep: number;
  extraPPAvailable?: boolean;
  extraPPUses?: number;
  extraPPActive?: boolean;
  deckCount?: number;
  handCount?: number;
  hand?: Entity[];
  field: Entity[];
  graveyard?: Entity[];
  resolving?: Entity[];
  banished?: Entity[];
  destroyed?: Entity[];
  shadows: number;
};
export type GameState = {
  revision?: number;
  viewer?: string;
  phase?: string;
  own: PlayerView;
  oppo: PlayerView;
  turn: { active: string; number: number };
  pendingChoice?: ChoiceRequest;
  gameOver?: boolean;
  winner?: string;
};
export type Remote = {
  sessionId: string;
  matchId?: string;
  playerToken?: string;
  joinCode?: string;
  side?: string;
  waiting?: boolean;
  matchPhase?: string;
  mulliganReady?: boolean;
  opponentReady?: boolean;
  state: GameState;
  legalActions?: LegalAction[];
  events?: RuntimeEvent[];
  result?: { status: string; errorCode?: string; illegalCode?: string };
};
